name: CI

on:
  pull_request:
  push:
    branches:
      - 0.*.x
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build and test frontend
        run: yarn build

  test-demo-builder-mode:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo/builder
    steps:
      - uses: actions/checkout@v3

      - name: Setup golang environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'

      - name: Install dependencies
        run: go mod download

      - name: Run test case 
        run: go test .
